[project]
name = "sentiment-stream"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.36.26",
    "matplotlib>=3.10.0",
    "mlflow>=2.20.2",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "zenml>=0.73.0",
]
